# Generated by Django 5.0.6 on 2024-06-23 09:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='hui', editable=False, populate_from='title', unique=True),
        ),
    ]
