# Generated by Django 5.0.6 on 2025-05-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
            ],
            options={
                'verbose_name': 'Код доступа',
                'verbose_name_plural': 'Коды доступа',
            },
        ),
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервера')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP адрес')),
                ('version', models.CharField(max_length=20, verbose_name='Версия Minecraft')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='online', max_length=20, verbose_name='Статус')),
                ('max_players', models.IntegerField(default=20, verbose_name='Максимальное количество игроков')),
                ('required_mods', models.TextField(blank=True, help_text='Формат: Название мода|URL (каждый мод с новой строки)', verbose_name='Обязательные моды (каждый с новой строки)')),
                ('optional_mods', models.TextField(blank=True, help_text='Формат: Название мода|URL (каждый мод с новой строки)', verbose_name='Необязательные моды (каждый с новой строки)')),
                ('enable_query', models.BooleanField(default=False, verbose_name='Включить Query')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='servers/favicons/')),
            ],
            options={
                'verbose_name': 'Minecraft сервер',
                'verbose_name_plural': 'Minecraft серверы',
            },
        ),
    ]
