# Generated by Django 5.0.6 on 2025-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сервера')),
                ('ip', models.CharField(max_length=100, verbose_name='IP адрес')),
                ('port', models.IntegerField(default=25565, verbose_name='Порт')),
                ('version', models.CharField(max_length=20, verbose_name='Версия Minecraft')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='online', max_length=20, verbose_name='Статус')),
                ('max_players', models.IntegerField(default=20, verbose_name='Максимальное количество игроков')),
                ('required_mods', models.TextField(blank=True, help_text='Формат: Название мода|URL (каждый мод с новой строки)', verbose_name='Обязательные моды (каждый с новой строки)')),
                ('optional_mods', models.TextField(blank=True, help_text='Формат: Название мода|URL (каждый мод с новой строки)', verbose_name='Необязательные моды (каждый с новой строки)')),
            ],
            options={
                'verbose_name': 'Minecraft сервер',
                'verbose_name_plural': 'Minecraft серверы',
            },
        ),
    ]
