# Generated by Django 5.0.6 on 2025-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='enable_panel_control',
            field=models.BooleanField(default=False, verbose_name='Включить управление через панель'),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='panel_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API ключ клиента с доступом'),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='panel_server_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID сервера в панели'),
        ),
        migrations.AddField(
            model_name='minecraftserver',
            name='panel_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL панели'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('maintenance', 'Maintenance'), ('starting', 'Starting'), ('stopping', 'Stopping')], default='online', max_length=20, verbose_name='Статус'),
        ),
    ]
