# Generated by Django 5.0.6 on 2025-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0002_minecraftserver_enable_panel_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='map_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
