# Generated by Django 5.0.6 on 2025-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0003_minecraftserver_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='game',
            field=models.CharField(default='Minecraft', max_length=100, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('starting', 'Starting'), ('stopping', 'Stopping')], default='online', max_length=20, verbose_name='Статус'),
        ),
    ]
