# Generated by Django 5.0.6 on 2025-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0004_minecraftserver_game_alter_minecraftserver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftserver',
            name='game',
            field=models.CharField(choices=[('minecraft', 'Minecraft'), ('halflife', 'Half-Life'), ('garrysmod', "Garry's Mod")], default='minecraft', max_length=20, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='minecraftserver',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Версия игры'),
        ),
    ]
